"""baseline_schema_completo

Revision ID: f9d6a18fef75
Revises:
Create Date: 2026-09-23 21:03:13.158333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d6a18fef75'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_financeiras',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('tipo_registro', sa.String(length=20), nullable=False),
    sa.Column('tipo_pessoa', sa.String(length=10), nullable=True),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('ie', sa.String(), nullable=True),
    sa.Column('inscricao_municipal', sa.String(), nullable=True),
    sa.Column('rg', sa.String(), nullable=True),
    sa.Column('id_estrangeiro', sa.String(), nullable=True),
    sa.Column('tipo_fiscal', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_nfe', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('telefone2', sa.String(), nullable=True),
    sa.Column('celular', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('fax', sa.String(), nullable=True),
    sa.Column('contato', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('codigo_ibge_municipio', sa.String(length=7), nullable=True),
    sa.Column('codigo_pais', sa.String(length=10), nullable=True),
    sa.Column('caixa_postal', sa.String(), nullable=True),
    sa.Column('atividade', sa.String(), nullable=True),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('grupo', sa.String(), nullable=True),
    sa.Column('situacao', sa.String(length=10), nullable=False),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('colunas_grade',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('situacao', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compras_financeiras',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fornecedor', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_compra', sa.Date(), nullable=False),
    sa.Column('numero_nf', sa.String(length=50), nullable=True),
    sa.Column('nf_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('condicoes_pagamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('condicao', sa.String(length=70), nullable=False),
    sa.Column('acrescimo', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('situacao', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('configuracao_custos_fixos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metros_rolo_overlock', sa.Integer(), nullable=False),
    sa.Column('custo_rolo_overlock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metros_rolo_reta', sa.Integer(), nullable=False),
    sa.Column('custo_rolo_reta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('custo_saquinho_lote', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unidades_saquinho_lote', sa.Integer(), nullable=False),
    sa.Column('custo_caixa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pecas_por_caixa', sa.Integer(), nullable=False),
    sa.Column('distancia_costureira_km', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('num_viagens', sa.Integer(), nullable=False),
    sa.Column('consumo_veiculo_km_l', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('preco_combustivel', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracao_empresa',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('aliquota_simples', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('custo_etiqueta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracao_grade',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('mascara', sa.String(length=100), nullable=False),
    sa.Column('separador', sa.String(length=5), nullable=False),
    sa.Column('tamanho_seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contas_bancarias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('ie', sa.String(length=30), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('endereco_numero', sa.String(length=20), nullable=True),
    sa.Column('endereco_bairro', sa.String(length=100), nullable=True),
    sa.Column('codigo_ibge_municipio', sa.String(length=7), nullable=True),
    sa.Column('codigo_pais', sa.String(length=10), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('telefone1', sa.String(length=20), nullable=True),
    sa.Column('telefone2', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('site', sa.String(length=100), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('regime_tributario', sa.String(length=30), nullable=False),
    sa.Column('uf_emitente', sa.String(length=2), nullable=False),
    sa.Column('ambiente_sefaz', sa.String(length=20), nullable=False),
    sa.Column('certificado_path', sa.String(length=500), nullable=True),
    sa.Column('certificado_senha', sa.String(length=500), nullable=True),
    sa.Column('nfe_serie_padrao', sa.String(length=10), nullable=False),
    sa.Column('nfe_numero_atual', sa.Integer(), nullable=False),
    sa.Column('nfce_serie_padrao', sa.String(length=10), nullable=False),
    sa.Column('nfce_numero_atual', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupos_produto',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('prefixo', sa.String(length=4), nullable=False),
    sa.Column('situacao', sa.String(length=10), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('linhas_grade',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('situacao', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metas_mensais',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('valor_meta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mes', 'ano', 'tipo', name='uq_meta_mensal_mes_ano_tipo')
    )
    op.create_table('modelos_tecido',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('max_camadas', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tabelas_grade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('situacao', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('tabelas_preco',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('comissao_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tecidos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('largura_util_cm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('gramatura_g_m2', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('valor_por_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('encolhimento_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estoque_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.Column('max_camadas', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('natureza_operacao', sa.String(length=200), nullable=False),
    sa.Column('cfop', sa.String(length=10), nullable=False),
    sa.Column('csosn', sa.String(length=3), nullable=False),
    sa.Column('cst_icms', sa.String(length=2), nullable=True),
    sa.Column('origem', sa.String(length=1), nullable=False),
    sa.Column('modalidade_bc_icms', sa.String(length=1), nullable=False),
    sa.Column('reducao_bc_icms', sa.Float(), nullable=False),
    sa.Column('aliquota_icms', sa.Float(), nullable=False),
    sa.Column('valor_icms', sa.Float(), nullable=False),
    sa.Column('pis_cst', sa.String(length=2), nullable=False),
    sa.Column('pis_aliquota', sa.Float(), nullable=False),
    sa.Column('cofins_cst', sa.String(length=2), nullable=False),
    sa.Column('cofins_aliquota', sa.Float(), nullable=False),
    sa.Column('gera_financeiro', sa.Boolean(), nullable=False),
    sa.Column('movimenta_estoque', sa.Boolean(), nullable=False),
    sa.Column('situacao', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('transportadoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('tipo_pessoa', sa.String(length=10), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('municipio', sa.String(), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('placa', sa.String(length=10), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('fax', sa.String(), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=True),
    sa.Column('rg_ie', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_nfe', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('contato', sa.String(), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.Column('bloqueado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vendas_financeiras',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cliente', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_venda', sa.Date(), nullable=False),
    sa.Column('numero_nf', sa.String(length=50), nullable=True),
    sa.Column('nf_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendedores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('tipo_pessoa', sa.String(length=10), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=150), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('municipio', sa.String(), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=True),
    sa.Column('rg_ie', sa.String(), nullable=True),
    sa.Column('inscricao_municipal', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('comissao_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('comissao_padrao_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('dia_pagto', sa.Integer(), nullable=False),
    sa.Column('pct_pago_emissao', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('pct_pago_baixa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('email_nfe', sa.String(length=100), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('catalogos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tabela_preco_id', sa.Uuid(), nullable=True),
    sa.Column('arquivo_path', sa.String(length=500), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tabela_preco_id'], ['tabelas_preco.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cores_tecido',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('modelo_id', sa.Uuid(), nullable=False),
    sa.Column('nome_cor', sa.String(length=50), nullable=False),
    sa.Column('largura_util_cm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('gramatura_g_m2', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('encolhimento_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_tecido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_tabela_grade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tabela_id', sa.Integer(), nullable=False),
    sa.Column('codigo_curto', sa.String(length=4), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['tabela_id'], ['tabelas_grade.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tabela_id', 'codigo_curto')
    )
    op.create_table('lancamentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_original', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parcela_numero', sa.Integer(), nullable=True),
    sa.Column('parcela_total', sa.Integer(), nullable=True),
    sa.Column('conta_bancaria_id', sa.Uuid(), nullable=True),
    sa.Column('categoria_id', sa.Uuid(), nullable=True),
    sa.Column('compra_id', sa.Uuid(), nullable=True),
    sa.Column('venda_id', sa.Uuid(), nullable=True),
    sa.Column('recorrente', sa.Boolean(), nullable=False),
    sa.Column('recorrencia_origem_id', sa.Uuid(), nullable=True),
    sa.Column('transferencia_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_financeiras.id'], ),
    sa.ForeignKeyConstraint(['compra_id'], ['compras_financeiras.id'], ),
    sa.ForeignKeyConstraint(['conta_bancaria_id'], ['contas_bancarias.id'], ),
    sa.ForeignKeyConstraint(['recorrencia_origem_id'], ['lancamentos.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas_financeiras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vendedor_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('segmento', sa.String(length=50), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='novo', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metas_vendedor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vendedor_id', sa.Uuid(), nullable=False),
    sa.Column('meta_ativacao', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bonus_logistica', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meta_novos_clientes', sa.Integer(), nullable=False),
    sa.Column('bonus_expansao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pedido_minimo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendedor_id')
    )
    op.create_table('pedidos_venda',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('prazo_entrega_dias', sa.Integer(), nullable=True),
    sa.Column('condicoes', sa.String(length=20), nullable=True),
    sa.Column('condicao_pagamento_id', sa.Integer(), nullable=True),
    sa.Column('primeiro_vencimento', sa.Date(), nullable=True),
    sa.Column('vendedor_id', sa.Uuid(), nullable=True),
    sa.Column('tabela_preco_id', sa.Uuid(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('cliente_razao_social', sa.String(length=200), nullable=True),
    sa.Column('cliente_cnpj', sa.String(length=20), nullable=True),
    sa.Column('cliente_ie', sa.String(length=30), nullable=True),
    sa.Column('cliente_endereco', sa.Text(), nullable=True),
    sa.Column('cliente_numero', sa.String(length=20), nullable=True),
    sa.Column('cliente_bairro', sa.String(length=100), nullable=True),
    sa.Column('cliente_cidade', sa.String(length=100), nullable=True),
    sa.Column('cliente_uf', sa.String(length=2), nullable=True),
    sa.Column('cliente_cep', sa.String(length=10), nullable=True),
    sa.Column('cliente_codigo_ibge_municipio', sa.String(length=7), nullable=True),
    sa.Column('cliente_codigo_pais', sa.String(length=10), nullable=True),
    sa.Column('cliente_telefone', sa.String(length=20), nullable=True),
    sa.Column('cliente_email', sa.String(length=100), nullable=True),
    sa.Column('representante', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_pedido', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('comissao_valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('comissao_pct', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('comissao_origem', sa.String(length=20), nullable=True),
    sa.Column('tes_id', sa.Integer(), nullable=True),
    sa.Column('desconto_geral_pct', sa.Float(), nullable=False),
    sa.Column('desconto_geral_valor', sa.Float(), nullable=False),
    sa.Column('acrescimo_pct', sa.Float(), nullable=False),
    sa.Column('acrescimo_valor', sa.Float(), nullable=False),
    sa.Column('valor_frete', sa.Float(), nullable=False),
    sa.Column('valor_seguro', sa.Float(), nullable=False),
    sa.Column('valor_despesas', sa.Float(), nullable=False),
    sa.Column('indicador_presenca', sa.String(length=20), nullable=False),
    sa.Column('informacoes_adicionais', sa.Text(), nullable=True),
    sa.Column('observacoes_internas', sa.Text(), nullable=True),
    sa.Column('nfe_id', sa.Integer(), nullable=True),
    sa.Column('transportadora_id', sa.Integer(), nullable=True),
    sa.Column('tipo_frete', sa.String(length=30), nullable=True),
    sa.Column('peso_liquido', sa.Float(), nullable=False),
    sa.Column('peso_bruto', sa.Float(), nullable=False),
    sa.Column('qtd_volumes', sa.Integer(), nullable=False),
    sa.Column('especie_volumes', sa.String(length=50), nullable=True),
    sa.Column('placa_veiculo', sa.String(length=10), nullable=True),
    sa.Column('uf_veiculo', sa.String(length=2), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['condicao_pagamento_id'], ['condicoes_pagamento.id'], ),
    sa.ForeignKeyConstraint(['tabela_preco_id'], ['tabelas_preco.id'], ),
    sa.ForeignKeyConstraint(['tes_id'], ['tes.id'], ),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('permissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('acao', sa.String(length=20), nullable=False),
    sa.Column('permitido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios_sistema.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('grupo_id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('almoxarifado', sa.String(length=10), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=False),
    sa.Column('segunda_unidade', sa.String(length=10), nullable=True),
    sa.Column('tipo_conversao', sa.String(length=30), nullable=True),
    sa.Column('fator_conversao', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('classe', sa.String(length=50), nullable=True),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('comissao_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('custo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margem_lucro_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ultimo_preco_compra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo_cod_barras', sa.String(length=20), nullable=True),
    sa.Column('cod_barras', sa.String(length=50), nullable=True),
    sa.Column('peso_gramas', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('peso_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('linha_grade_id', sa.Integer(), nullable=True),
    sa.Column('coluna_grade_id', sa.Integer(), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('tamanhos_disponiveis', sa.JSON(), nullable=True),
    sa.Column('ncm', sa.String(length=8), nullable=True),
    sa.Column('cest', sa.String(length=10), nullable=True),
    sa.Column('origem', sa.Integer(), nullable=False),
    sa.Column('icms_incidencia', sa.String(length=20), nullable=False),
    sa.Column('aliquota_ipi_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('codigo_iss', sa.String(length=20), nullable=True),
    sa.Column('cod_trib_iss', sa.String(length=20), nullable=True),
    sa.Column('cod_cnae', sa.String(length=20), nullable=True),
    sa.Column('base_icms_st_ret', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_icms_st_ret', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('base_fcp_st_ret', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('aliq_fcp_st_ret_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valor_fcp_st_ret', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('nat_receita', sa.String(length=50), nullable=True),
    sa.Column('tes_entrada_id', sa.Integer(), nullable=True),
    sa.Column('tes_saida_id', sa.Integer(), nullable=True),
    sa.Column('codigo_anp', sa.String(length=20), nullable=True),
    sa.Column('conta_contabil', sa.String(length=50), nullable=True),
    sa.Column('cod_fci', sa.String(length=50), nullable=True),
    sa.Column('valor_importacao', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('inf_adicionais', sa.String(length=1000), nullable=True),
    sa.Column('inventario_sped', sa.Boolean(), nullable=False),
    sa.Column('fcp', sa.Boolean(), nullable=False),
    sa.Column('um_faturamento', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['coluna_grade_id'], ['tabelas_grade.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_produto.id'], ),
    sa.ForeignKeyConstraint(['linha_grade_id'], ['tabelas_grade.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('saldo_inicial_conta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conta_bancaria_id', sa.Uuid(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['conta_bancaria_id'], ['contas_bancarias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conta_bancaria_id', 'mes', 'ano', name='uq_saldo_inicial_conta_mes_ano')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vendedor_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('vendedor_id')
    )
    op.create_table('vendedor_tabela_comissao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vendedor_id', sa.Uuid(), nullable=False),
    sa.Column('tabela_preco_id', sa.Uuid(), nullable=False),
    sa.Column('comissao_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('comissao_pct >= 0 AND comissao_pct <= 100', name='ck_vendedor_tabela_comissao_pct'),
    sa.ForeignKeyConstraint(['tabela_preco_id'], ['tabelas_preco.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendedor_id', 'tabela_preco_id', name='uq_vendedor_tabela_comissao')
    )
    op.create_table('anexos_lancamento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lancamento_id', sa.Uuid(), nullable=False),
    sa.Column('arquivo_path', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nome_original', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogo_vendedor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('catalogo_id', sa.Uuid(), nullable=False),
    sa.Column('vendedor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['catalogo_id'], ['catalogos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalogo_id', 'vendedor_id', name='uq_catalogo_vendedor')
    )
    op.create_table('grupos_molde',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('produto_id', sa.Uuid(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('lotes_tecido',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cor_id', sa.Uuid(), nullable=False),
    sa.Column('codigo_lote', sa.String(length=50), nullable=False),
    sa.Column('peso_inicial_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('peso_disponivel_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('valor_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_compra', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cor_id'], ['cores_tecido.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_lote')
    )
    op.create_table('notas_fiscais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.Uuid(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=2), nullable=False),
    sa.Column('ambiente', sa.String(length=20), nullable=False),
    sa.Column('chave_acesso', sa.String(length=44), nullable=True),
    sa.Column('protocolo', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valor_nf', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('xml_path', sa.String(length=500), nullable=True),
    sa.Column('danfe_path', sa.String(length=500), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=False),
    sa.Column('data_saida', sa.DateTime(), nullable=True),
    sa.Column('hora_saida', sa.String(length=8), nullable=True),
    sa.Column('data_autorizacao', sa.DateTime(), nullable=True),
    sa.Column('motivo_rejeicao', sa.Text(), nullable=True),
    sa.Column('carta_correcao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_venda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos_sku',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_pai_id', sa.Uuid(), nullable=False),
    sa.Column('linha_item_id', sa.Integer(), nullable=True),
    sa.Column('coluna_item_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preco_manual', sa.Boolean(), nullable=False),
    sa.Column('situacao', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coluna_item_id'], ['itens_tabela_grade.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['linha_item_id'], ['itens_tabela_grade.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_pai_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('produto_pai_id', 'linha_item_id', 'coluna_item_id')
    )
    op.create_table('encaixes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pedido_id', sa.Uuid(), nullable=True),
    sa.Column('lote_id', sa.Uuid(), nullable=True),
    sa.Column('tecido_id', sa.Uuid(), nullable=True),
    sa.Column('mapa_json', sa.JSON(), nullable=True),
    sa.Column('comp_metros', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('peso_kg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('custo_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('desperdicio_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('num_camadas', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('data_corte', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_tecido.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_venda.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tecido_id'], ['tecidos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_pedido',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pedido_id', sa.Uuid(), nullable=False),
    sa.Column('grupo_id', sa.Uuid(), nullable=True),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.Column('lote_id', sa.Uuid(), nullable=True),
    sa.Column('qtd_p', sa.Integer(), nullable=False),
    sa.Column('qtd_m', sa.Integer(), nullable=False),
    sa.Column('qtd_g', sa.Integer(), nullable=False),
    sa.Column('qtd_gg', sa.Integer(), nullable=False),
    sa.Column('qtd_g1', sa.Integer(), nullable=False),
    sa.Column('qtd_g2', sa.Integer(), nullable=False),
    sa.Column('qtd_g3', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_manual', sa.Boolean(), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('tes_id', sa.Integer(), nullable=True),
    sa.Column('desconto_pct', sa.Float(), nullable=False),
    sa.Column('desconto_valor', sa.Float(), nullable=False),
    sa.Column('desconto_percentual', sa.Numeric(precision=7, scale=4), server_default='0', nullable=False),
    sa.Column('desconto_tipo', sa.String(length=10), server_default='VALOR', nullable=False),
    sa.Column('acrescimo_pct', sa.Float(), nullable=False),
    sa.Column('acrescimo_valor', sa.Float(), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_molde.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_tecido.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_venda.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['produtos_sku.id'], ),
    sa.ForeignKeyConstraint(['tes_id'], ['tes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moldes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('arquivo_path', sa.String(length=500), nullable=True),
    sa.Column('formato', sa.String(length=10), nullable=True),
    sa.Column('peca', sa.String(length=100), nullable=True),
    sa.Column('tamanho', sa.String(length=10), nullable=True),
    sa.Column('sentido_fio', sa.String(length=20), nullable=True),
    sa.Column('tipo_corte', sa.String(length=20), nullable=False),
    sa.Column('rotacao_base', sa.Integer(), server_default='0', nullable=False),
    sa.Column('area_cm2', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('geometria_json', sa.JSON(), nullable=True),
    sa.Column('grupo_id', sa.Uuid(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_molde.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precificacoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('grupo_id', sa.Uuid(), nullable=False),
    sa.Column('tamanho', sa.String(length=10), nullable=False),
    sa.Column('faixa_tamanho', sa.String(length=20), nullable=False),
    sa.Column('valor_kg_tecido', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pecas_por_kg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('custo_tecido_manual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custo_tecido_encaixe', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('usar_custo_encaixe', sa.Boolean(), nullable=False),
    sa.Column('custo_costura', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metros_linha_overlock', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('metros_linha_reta', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('pecas_por_viagem', sa.Integer(), nullable=False),
    sa.Column('margem_desejada', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('preco_venda_sugerido', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preco_venda_final', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_molde.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('precificacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_precificacoes_grupo_id'), ['grupo_id'], unique=False)

    op.create_table('precos_referencia',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('grupo_id', sa.Uuid(), nullable=False),
    sa.Column('tabela_id', sa.Uuid(), nullable=False),
    sa.Column('preco_avista', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_aprazo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tem_plus_size', sa.Boolean(), nullable=False),
    sa.Column('preco_avista_plus', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preco_aprazo_plus', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_molde.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tabela_id'], ['tabelas_preco.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grupo_id', 'tabela_id', name='uq_preco_ref_grupo_tabela')
    )
    op.create_table('precos_tabela_produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tabela_preco_id', sa.Uuid(), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('preco_avista', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_aprazo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tem_plus_size', sa.Boolean(), nullable=False),
    sa.Column('preco_avista_plus', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preco_aprazo_plus', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(produto_id IS NOT NULL AND sku_id IS NULL) OR (produto_id IS NULL AND sku_id IS NOT NULL)', name='ck_preco_tab_prod_produto_xor_sku'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['produtos_sku.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tabela_preco_id'], ['tabelas_preco.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tabela_preco_id', 'produto_id', name='uq_preco_tab_prod_produto'),
    sa.UniqueConstraint('tabela_preco_id', 'sku_id', name='uq_preco_tab_prod_sku')
    )
    op.create_table('consumos_lote',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lote_id', sa.Uuid(), nullable=False),
    sa.Column('encaixe_id', sa.Uuid(), nullable=True),
    sa.Column('pedido_id', sa.Uuid(), nullable=True),
    sa.Column('peso_planejado_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('peso_retalho_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('data_consumo', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['encaixe_id'], ['encaixes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_tecido.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_venda.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defeitos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('encaixe_id', sa.Uuid(), nullable=False),
    sa.Column('x_cm', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('y_cm', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('raio_cm', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['encaixe_id'], ['encaixes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('defeitos')
    op.drop_table('consumos_lote')
    op.drop_table('precos_tabela_produto')
    op.drop_table('precos_referencia')
    with op.batch_alter_table('precificacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_precificacoes_grupo_id'))

    op.drop_table('precificacoes')
    op.drop_table('moldes')
    op.drop_table('itens_pedido')
    op.drop_table('encaixes')
    op.drop_table('produtos_sku')
    op.drop_table('notas_fiscais')
    op.drop_table('lotes_tecido')
    op.drop_table('grupos_molde')
    op.drop_table('catalogo_vendedor')
    op.drop_table('anexos_lancamento')
    op.drop_table('vendedor_tabela_comissao')
    op.drop_table('usuarios')
    op.drop_table('saldo_inicial_conta')
    op.drop_table('produtos')
    op.drop_table('permissoes')
    op.drop_table('pedidos_venda')
    op.drop_table('metas_vendedor')
    op.drop_table('leads')
    op.drop_table('lancamentos')
    op.drop_table('itens_tabela_grade')
    op.drop_table('cores_tecido')
    op.drop_table('catalogos')
    op.drop_table('vendedores')
    op.drop_table('vendas_financeiras')
    op.drop_table('usuarios_sistema')
    op.drop_table('transportadoras')
    op.drop_table('tes')
    op.drop_table('tecidos')
    op.drop_table('tabelas_preco')
    op.drop_table('tabelas_grade')
    op.drop_table('modelos_tecido')
    op.drop_table('metas_mensais')
    op.drop_table('linhas_grade')
    op.drop_table('grupos_produto')
    op.drop_table('empresa')
    op.drop_table('contas_bancarias')
    op.drop_table('configuracao_grade')
    op.drop_table('configuracao_empresa')
    op.drop_table('configuracao_custos_fixos')
    op.drop_table('condicoes_pagamento')
    op.drop_table('compras_financeiras')
    op.drop_table('colunas_grade')
    op.drop_table('clientes')
    op.drop_table('categorias_financeiras')
    # ### end Alembic commands ###
